# Generated by Django 2.2.2 on 2019-07-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_auto_20190710_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
