# Generated by Django 2.2.2 on 2019-07-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_auto_20190716_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image',
            new_name='image1',
        ),
    ]
